
from django.urls import path, include,re_path
from . import views
from .import HodViews, StaffViews, StudentViews


urlpatterns = [
    path('', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', HodViews.admin_home, name="admin_home"),
    path('admin_view_attendance/', HodViews.admin_view_attendance, name="admin_view_attendance"),
    path('admin_profile/', HodViews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', HodViews.admin_profile_update, name="admin_profile_update"),
    path('check_email_exist/', HodViews.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', HodViews.check_username_exist, name="check_username_exist"),
    path('add_receipt/', HodViews.add_receipt, name="add_receipt"),
    path('add_receipt_save/', HodViews.add_receipt_save, name="add_receipt_save"),
    path('manage_receipt/', HodViews.manage_receipt, name="manage_receipt"),
    path('edit_receipt/<receipt_id>/', HodViews.edit_receipt, name="edit_receipt"),
    path('edit_receipt_save/', HodViews.edit_receipt_save, name="edit_receipt_save"),
    path('delete_receipt/<receipt_id>/', HodViews.delete_receipt, name="delete_receipt"),
    path('add_task/', HodViews.add_task, name="add_task"),
    path('manage_sample/', HodViews.manage_sample, name="manage_sample"),
    path('add_remarks/<remarks_id>', HodViews.add_remarks, name="add_remarks"),
    path('add_remarks_save/', HodViews.add_remarks_save, name="add_remarks_save"),
    path('edit_sample/<sample_id>/', HodViews.edit_sample, name="edit_sample"),
    path('edit_sample_save/', HodViews.edit_sample_save, name="edit_sample_save"),
    path('sample_approve/', HodViews.sample_approve, name="sample_approve"),
    path('manage_task/', HodViews.manage_task, name="manage_task"),
    path('add_certification/', HodViews.add_certification, name="add_certification"),
    path('manage_certification/', HodViews.manage_certification, name="manage_certification"),
    path('print_certification/<cid>', HodViews.print_certification, name="print_certification"),
    path('fail_certification/', HodViews.fail_certification, name="fail_certification"),
    path('show_certification/<cid>', HodViews.show_certification, name="show_certification"),
    path('add_identification_staff/', HodViews.add_identification_staff, name="add_identification_staff"),
    path('add_member/', HodViews.add_member, name="add_member"),
    path('add_member_save/', HodViews.add_member_save, name="add_member_save"),
    path('manage_member/', HodViews.manage_member, name="manage_member"),
    path('edit_member/<member_id>/', HodViews.edit_member, name="edit_member"),
    path('edit_member_save/', HodViews.edit_member_save, name="edit_member_save"),
    path('delete_member/<member_id>/', HodViews.delete_member, name="delete_member"),
    path('search_tel/', HodViews.search_tel, name="search_tel"),
    path('manage_excel/', HodViews.manage_excel, name="manage_excel"),
    #【系统管理的】所有路由配置
    path('manage_system/', HodViews.manage_system, name="manage_system"),
    path('a1/', HodViews.a1, name="a1"),
    path('a2/', HodViews.a2, name="a2"),
    path('a3/', HodViews.a3, name="a3"),
    path('a4/', HodViews.a4, name="a4"),
    path('a5/', HodViews.a5, name="a5"),
    path('a6/', HodViews.a6, name="a6"),
    path('a7/', HodViews.a7, name="a7"),

    #a1
    path('delete_usergroup/<usergroup_id>/', HodViews.delete_usergroup, name="delete_usergroup"),
    path('add_usergroup/', HodViews.add_usergroup, name="add_usergroup"),
    path('add_usergroup_save/', HodViews.add_usergroup_save, name="add_usergroup_save"),
    path('edit_usergroup/<usergroup_id>/', HodViews.edit_usergroup, name="edit_usergroup"),
    path('edit_usergroup_save/', HodViews.edit_usergroup_save, name="edit_usergroup_save"),
    path('add_user_save/', HodViews.add_user_save, name="add_user_save"),
    path('edit_user/<user_id>/', HodViews.edit_user, name="edit_user"),
    path('edit_user_save/', HodViews.edit_user_save, name="edit_user_save"),
    path('delete_user/<user_id>/', HodViews.delete_user, name="delete_user"),
    #a2
    path('edit_systemsetting_save/', HodViews.edit_systemsetting_save, name="edit_systemsetting_save"),
    #a3
    path('backup/', HodViews.backup, name="backup"),
    #a4
    path('delete_usergroupstatus/<usergroupstatus_id>/',HodViews.delete_usergroupstatus,name="delete_usergroupstatus"),
    path('add_usergroupstatus/', HodViews.add_usergroupstatus, name="add_usergroupstatus"),
    path('add_usergroupstatus_save/', HodViews.add_usergroupstatus_save, name="add_usergroupstatus_save"),
    path('edit_usergroupstatus/<usergroupstatus_id>/', HodViews.edit_usergroupstatus, name="edit_usergroupstatus"),
    path('edit_usergroupstatus_save/', HodViews.edit_usergroupstatus_save, name="edit_usergroupstatus_save"),
    #a5
    path('delete_preinstall/<preinstall_id>/',HodViews.delete_preinstall,name="delete_preinstall"),
    path('add_preinstall/', HodViews.add_preinstall, name="add_preinstall"),
    path('add_preinstall_save/', HodViews.add_preinstall_save, name="add_preinstall_save"),
    path('edit_preinstall/<preinstall_id>/', HodViews.edit_preinstall, name="edit_preinstall"),
    path('edit_preinstall_save/', HodViews.edit_preinstall_save, name="edit_preinstall_save"),
    # a6
    path('delete_membertype/<membertype_id>/', HodViews.delete_membertype, name="delete_membertype"),
    path('add_membertype/', HodViews.add_membertype, name="add_membertype"),
    path('add_membertype_save/', HodViews.add_membertype_save, name="add_membertype_save"),
    path('edit_membertype/<membertype_id>/', HodViews.edit_membertype, name="edit_membertype"),
    path('edit_membertype_save/', HodViews.edit_membertype_save, name="edit_membertype_save"),


    # URLS for Staff
    path('staff_home/', StaffViews.staff_home, name="staff_home"),
    path('staff_take_attendance/', StaffViews.staff_take_attendance, name="staff_take_attendance"),
    path('get_students/', StaffViews.get_students, name="get_students"),
    path('save_attendance_data/', StaffViews.save_attendance_data, name="save_attendance_data"),
    path('staff_update_attendance/', StaffViews.staff_update_attendance, name="staff_update_attendance"),
    path('get_attendance_dates/', StaffViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student/', StaffViews.get_attendance_student, name="get_attendance_student"),
    path('update_attendance_data/', StaffViews.update_attendance_data, name="update_attendance_data"),
    path('staff_apply_leave/', StaffViews.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save/', StaffViews.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback/', StaffViews.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save/', StaffViews.staff_feedback_save, name="staff_feedback_save"),
    path('staff_profile/', StaffViews.staff_profile, name="staff_profile"),
    path('staff_profile_update/', StaffViews.staff_profile_update, name="staff_profile_update"),
    path('staff_add_result/', StaffViews.staff_add_result, name="staff_add_result"),
    path('staff_add_result_save/', StaffViews.staff_add_result_save, name="staff_add_result_save"),

    # URSL for Student
    path('student_home/', StudentViews.student_home, name="student_home"),
    path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_apply_leave/', StudentViews.student_apply_leave, name="student_apply_leave"),
    path('student_apply_leave_save/', StudentViews.student_apply_leave_save, name="student_apply_leave_save"),
    path('student_feedback/', StudentViews.student_feedback, name="student_feedback"),
    path('student_feedback_save/', StudentViews.student_feedback_save, name="student_feedback_save"),
    path('student_profile/', StudentViews.student_profile, name="student_profile"),
    path('student_profile_update/', StudentViews.student_profile_update, name="student_profile_update"),
    path('student_view_result/', StudentViews.student_view_result, name="student_view_result"),
]
