# Generated by Django 3.1.3 on 2020-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0006_auto_20201125_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mession',
            fields=[
                ('identification_id', models.TextField(primary_key=True, serialize=False)),
                ('receipt_tel', models.TextField()),
                ('sample_status', models.TextField()),
                ('sender_company', models.TextField()),
                ('sender', models.TextField()),
                ('sender_tel', models.TextField()),
                ('postal_code', models.TextField()),
                ('gemstone_sum', models.TextField()),
                ('basket_id', models.TextField()),
                ('finish_date', models.DateTimeField()),
                ('identification_cost', models.FloatField()),
                ('payment_state', models.BooleanField()),
                ('sample_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('identification_id', models.TextField(primary_key=True, serialize=False)),
                ('receipt_tel', models.TextField()),
                ('sample_status', models.TextField()),
                ('sender_company', models.TextField()),
                ('sender', models.TextField()),
                ('sender_tel', models.TextField()),
                ('postal_code', models.TextField()),
                ('gemstone_sum', models.TextField()),
                ('basket_id', models.TextField()),
                ('finish_date', models.DateTimeField()),
                ('identification_cost', models.FloatField()),
                ('payment_state', models.BooleanField()),
                ('sample_date', models.DateTimeField()),
            ],
        ),
    ]
