# Generated by Django 3.1.3 on 2020-11-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0007_mession_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_recipt',
            fields=[
                ('identification_id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('basket_id', models.TextField(max_length=20)),
                ('send_date', models.TextField(max_length=20)),
                ('finish_date', models.TextField(max_length=20)),
                ('sample_status', models.TextField(max_length=20)),
                ('identification_cost', models.TextField(max_length=20)),
                ('payment_state', models.IntegerField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_company', models.TextField(max_length=30)),
                ('name', models.TextField(max_length=20)),
                ('tel', models.TextField(max_length=20)),
                ('postal_code', models.TextField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Mession',
        ),
        migrations.AlterField(
            model_name='receipts',
            name='sample_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='sample_recipt',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gem_Manage_App.sender'),
        ),
    ]
