# Generated by Django 3.1.3 on 2020-11-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0014_auto_20201128_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlesample',
            name='is_select',
            field=models.BooleanField(default=False),
        ),
    ]
