# Generated by Django 3.1.3 on 2020-11-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0017_singlesample_singlesample_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlesample',
            name='SingleSample_status',
            field=models.CharField(default='收样', max_length=20),
        ),
    ]
