# Generated by Django 3.1.3 on 2020-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0018_auto_20201129_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
