# Generated by Django 3.1.3 on 2020-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0019_auto_20201129_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpower',
            name='is_editable',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='non_active', max_length=32, verbose_name='是否有编辑权限'),
        ),
        migrations.AlterField(
            model_name='userpower',
            name='is_forbidden',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='non_active', max_length=32, verbose_name='是否禁止访问'),
        ),
        migrations.AlterField(
            model_name='userpower',
            name='is_readable',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='non_active', max_length=32, verbose_name='是否有浏览权限'),
        ),
    ]
