# Generated by Django 3.1.3 on 2020-11-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0020_auto_20201129_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
