# Generated by Django 3.1.3 on 2020-11-29 14:53

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0021_auto_20201129_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='payment_state',
            field=models.CharField(choices=[(1, '是'), (2, '否')], default='是', max_length=10, verbose_name='是否付款'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
