# Generated by Django 3.1.3 on 2020-12-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0023_auto_20201203_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_name', models.CharField(max_length=20)),
                ('copy_date', models.DateField()),
                ('copy_position', models.FilePathField()),
                ('copyfile_name', models.CharField(max_length=50)),
                ('copy_remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopySetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_method', models.IntegerField()),
                ('copy_type', models.CharField(max_length=10)),
                ('copy_cycle', models.IntegerField(null=True)),
                ('copy_hour', models.IntegerField(null=True)),
                ('starttime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_x', models.IntegerField()),
                ('start_y', models.IntegerField()),
                ('row_spacing', models.IntegerField()),
                ('col_spacing', models.IntegerField()),
                ('page_spacing', models.IntegerField()),
                ('row_words', models.IntegerField()),
                ('row_max', models.IntegerField()),
                ('picture_x', models.IntegerField()),
                ('picture_y', models.IntegerField()),
                ('pic_sizex', models.IntegerField()),
                ('pic_sizey', models.IntegerField()),
                ('QR_X', models.IntegerField()),
                ('QR_Y', models.IntegerField()),
                ('QR_size', models.IntegerField()),
                ('page_sizex', models.IntegerField()),
                ('page_sizey', models.IntegerField()),
                ('font', models.IntegerField()),
                ('horizontal', models.IntegerField()),
                ('name', models.CharField(default='1', max_length=20, verbose_name='表单名')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_letter', models.CharField(max_length=2)),
                ('station_num', models.IntegerField()),
                ('now_position', models.CharField(max_length=5)),
                ('now_number', models.IntegerField()),
                ('feature_type', models.CharField(max_length=5)),
                ('feature_digit', models.IntegerField()),
                ('image_add', models.FilePathField()),
                ('pic_size', models.CharField(max_length=20)),
                ('QR_add', models.URLField()),
                ('page_size', models.IntegerField()),
                ('read_type', models.IntegerField()),
                ('gorge', models.CharField(max_length=10)),
                ('baud_rate', models.IntegerField()),
                ('parity_check', models.IntegerField()),
                ('data_bit', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('stop_bit', models.CharField(max_length=10)),
                ('hand_control', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='member_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gem_Manage_App.membertype'),
        ),
        migrations.AlterField(
            model_name='membertype',
            name='status',
            field=models.TextField(verbose_name='会员类型状态'),
        ),
    ]
