# Generated by Django 3.1.3 on 2020-12-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gem_Manage_App', '0025_auto_20201214_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupstatus',
            name='usergroup_status_values',
            field=models.CharField(max_length=50, verbose_name='配置状态'),
        ),
    ]
